spring:
  application:
    name: weshopify-product-service
  h2:
    console:
      enabled: true
      path: /h2Console
  datasource:
    url: jdbc:h2:mem:products
    username: sa
    password: 
    
    
server:
  port: 5023
  
