spring:
  application:
    name: ${APP_NAME:weshopify-authn-service}
  data:
    redis:
      host: ${REDIS_SERVER_HOST:cache.weshopifyapp.in}
      port: ${REDIS_SERVER_PORT:80}
      password: ${REDIS_SERVER_PASSWORD:Redis123$}
server:
  port: ${AUTHN_SERVICE_PORT:5022}
  
weshopify-platform:
  scim2: 
   usersUri: https://${WSO2_SERVER_HOST_NAME:iam.weshopifyapp.in}/scim2/Users/ 
  oauth2: 
    uri: https://${WSO2_SERVER_HOST_NAME:iam.weshopifyapp.in}/oauth2/token
    logoutUri: https://${WSO2_SERVER_HOST_NAME:iam.weshopifyapp.in}/oauth2/revoke
    userInfoUri: https://${WSO2_SERVER_HOST_NAME:iam.weshopifyapp.in}/oauth2/userinfo?schema=
    grant_type: ${GRANT_TYPE:password}
    scope: ${SCOPE:openid}
    clientId: ${CLIENT_ID:QLGGcnm3X3aW61N0uFEc8uKq_FAa}
    clientSecret: ${CLIENT_SECRET:3kqsCWj64H6O4szaJDfmYwEdvBka}