global:
  scrape_interval: 10s #Prometheus sends an HTTP request (pull) called Scrape to application and as well grapaha
  evaluation_interval: 10s #How frequently to evaluate rules by default it is 1m.

scrape_configs:

  - job_name: "prometheous-server"
    metrics_path: /metrics
    static_configs:
     - targets: ['52.66.125.230:9090'] # the ip adress of the docker engine 
                                       # where the prometheous is running as docker container
     
  - job_name: "weshopify-usermgmt-service"
    metrics_path: /actuator/prometheus
    static_configs:
     - targets: ['13.233.80.112:5014'] # the ip address of the vm machine 
                                       # where the weshopify-user-mgmt app is running
      
      
rule_files:
 # - "metrics-rules.yml"
 # - "alters-rules.yml"
 
 