version: '3.9'
services:

 weshopify-categories-db-svc: 
   container_name: weshopify-categories-db
   image: mysql:latest
   restart: always
   ports:
     - 3306:3306
   environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=weshopify-categories
 
 weshopify-registry-svc: 
  container_name: weshopify-registry
  image: weshopify-service-registry-img
  restart: on-failure
  ports:
    - 8761:8761
  environment: 
   - REGISTRY_PREF_IP=false

 weshopify-axon-server: 
  container_name: weshopify-event-store
  image: axoniq/axonserver
  ports:
    - 8124:8124
    - 8024:8024
 
 weshopify-authn-svc: 
  container_name: weshopify-authn-service
  image: weshopify-auth-svc-img
  restart: on-failure
  ports:
    - 5022:5022
  environment: 
   - WSO2_SERVER_HOST_NAME=iam.weshopifyapp.in
   - GRANT_TYPE=password
   - SCOPE=openid
   - CLIENT_ID=QLGGcnm3X3aW61N0uFEc8uKq_FAa
   - CLIENT_SECRET=3kqsCWj64H6O4szaJDfmYwEdvBka
   - REDIS_SERVER_HOST=cache.weshopifyapp.in
   - REDIS_SERVER_PORT=80
   - REDIS_SERVER_PASSWORD:Redis123$$

 weshopify-user-mgmt-svc: 
  container_name: weshopify-user-mgmt-svc
  image: weshopify-user-mgmt-img
  restart: on-failure
  ports:
    - 5014:5014
  environment:
   - WSO2_SERVER_HOST_NAME=iam.weshopifyapp.in
   - WSO2_SERVER_USER_NAME=admin
   - WSO2_SERVER_USER_PASSWORD=admin

 weshopify-categories-svc: 
  container_name: weshopify-categories-svc
  image: weshopify-categories-svc-img
  restart: on-failure
  ports:
    - 5016:5016
  environment: 
   - CATEGOIRIES_DB_HOST=weshopify-categories-db-svc
   - CATEGORIES_DB_PASSWORD=root
   - CATEGORIES_DB_SCHEMA=weshopify-categories
   - REDIS_SERVER_HOST=cache.weshopifyapp.in
   - REDIS_SERVER_PORT=80
   - REDIS_SERVER_PASSWORD=Redis123$$
   - SERVICE_REGISTRY_HOST=weshopify-registry-svc
   - SERVICE_REGISTRY_PORT=8761
   - AXON_SERVER_HOST=weshopify-axon-server
   - AXON_SERVER_PORT=8124

 weshopify-brands-svc: 
  container_name: weshopify-brands-svc
  image: weshopify-brands-svc-img
  restart: on-failure
  ports:
    - 5017:5017
  environment: 
   - MONGO_DB_URI=mongodb+srv://mongo:mongo@cluster0.eczp2kn.mongodb.net/?retryWrites=true&w=majority
   - MONGO_AUTO_INDEX_CREATION=true
   - REDIS_SERVER_HOST=cache.weshopifyapp.in
   - REDIS_SERVER_PORT=80
   - REDIS_SERVER_PASSWORD=Redis123$$
   - SERVICE_REGISTRY_HOST=weshopify-registry-svc
   - SERVICE_REGISTRY_PORT=8761
   - AXON_SERVER_HOST=weshopify-axon-server
   - AXON_SERVER_PORT=8124
   - CATEGORIES_SVC_HOST=weshopify-categories-svc
   - CATEGORIES_SVC_PORT=5016
   - ZIPKIN_HOST=weshopify-zipkin-service
   - ZIPKIN_PORT=9411

 weshopify-gateway-svc: 
  container_name: weshopify-gateway-svc
  image: weshopify-gateway-svc-img
  restart: on-failure
  ports:
    - 5012:5012
  environment: 
   - SERVICE_REGISTRY_HOST=weshopify-registry-svc
   - SERVICE_REGISTRY_PORT=8761

 weshopify-zipkin-service: 
  container_name: zipkin
  image: openzipkin/zipkin
  restart: on-failure
  ports:
    - 9411:9411

     
