spring: 
 application: 
   name: weshopify-category-service
 datasource: 
   username: '${CATEGORIES_DB_USER:root}'
   password: '${CATEGORIES_DB_PASSWORD:root}' 
   url: 'jdbc:${CATEGORIES_DB_TYPE:mysql}://${CATEGOIRIES_DB_HOST:localhost}:${CATEGORIES_DB_PORT:3306}/${CATEGORIES_DB_SCHEMA:weshopify_app_categories}'
 jpa:
    hibernate:
      ddl-auto: '${CATEGORIES_DB_DDL_AUTO:update}'
    show-sql: true    
 data:
    redis:
      host: '${REDIS_SERVER_HOST:cache.weshopifyapp.in}'
      port: '${REDIS_SERVER_PORT:80}'
      password: '${REDIS_SERVER_PASSWORD:Redis123$}'
      
eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka/
  instance:
    hostname: ${SERVICE_REGISTRY_HOST:localhost}
    prefer-ip-address: true
axon:
  axonserver:
    #servers: '${AXON_SERVER_HOST:localhost}:${AXON_SERVER_PORT:8024}'
    servers: localhost:8024

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing: 
     sampling: 
        probability: 1.0

   
server:
    port: 5016
    
logging:
   pattern: 
     level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    
resilience4j:
  circuitbreaker:
    configs:
      default: 
        register-health-indicator: true
    instances:
      catgories-circuit: 
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000
        permitted-number-of-calls-in-half-open-state: 2
